/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * SWAPI
 * API documentation for Star Wars API - SWAPI
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
export type GetPeopleParams = {
    search?: string;
    page?: number;
};

export interface Person {
    birth_year: string;
    name: string;
    url: string;
}

export interface PeopleResponse {
    count: number;
    results: Person[];
}

/**
 * @summary Get all people in all movies
 */
export const getPeople = <TData = AxiosResponse<PeopleResponse>>(
    params?: GetPeopleParams,
    options?: AxiosRequestConfig,
): Promise<TData> => {
    return axios.get(`https://swapi.dev/api/people`, {
        ...options,
        params: { ...params, ...options?.params },
    });
};

/**
 * @summary Get one person by id
 */
export const getPerson = <TData = AxiosResponse<Person>>(id: string, options?: AxiosRequestConfig): Promise<TData> => {
    return axios.get(`https://swapi.dev/api/people/${id}`, options);
};

export type GetPeopleResult = AxiosResponse<PeopleResponse>;
export type GetPersonResult = AxiosResponse<Person>;
